name = "api"
compatibility_date = "2024-08-21"
# compatibility_flags = [ "nodejs_compat" ]
node_compat = true



[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTkwNDA2NGUtMDYwOC00NzkxLTk3YWMtNTAwMGVhYmYwNDgwIiwidGVuYW50X2lkIjoiNDVkZDhmZjZlZDc3ZWM0YTNiMTA5ZWEyY2UzOTNiMmQ0YmQ0OTU5NGQ5YzIyNGQ4MzFkYzllZGFlOWZkOGYwOCIsImludGVybmFsX3NlY3JldCI6ImZhYzg2NTFjLTA4ODEtNDI1MS05ZmZjLTRkNzcxYzk2Njg2MCJ9.6w-F9c7DwDAnX2X2JD2y7j6G0N_6DZPtAF681QhSE-M"
JWT_SECRET = "bruh"
TWILIO_PHONE_NUMBER="7543933647"
TWILIO_AUTH_TOKEN="32b5acb774792ade2d4ebc9a547d30f5"
TWILIO_ACCOUNT_SID="ACc4201677df835c9781d9817aab20ad1a"
