name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - '**'

jobs:

  Continuous-Integration:

    name: Performs linting, formatting on the application
    needs: install-pnpm/cache-and-install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Run linting check
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format
