name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - '**'

jobs:

  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.9.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

  Continuous-Integration:

    name: Performs linting, formatting on the application
    needs: cache-and-install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Run linting check
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format
